// Details
export const ACTION_DETAILS_REQUEST = 'ACTION_DETAILS_REQUEST';
export const ACTION_DETAILS_SUCCESS = 'ACTION_DETAILS_SUCCESS';
export const ACTION_DETAILS_FAIL = 'ACTION_DETAILS_FAIL';
export const ACTION_DETAILS_RESET = 'ACTION_DETAILS_RESET';

// Saved
export const SAVED_ACTIONS_REQUEST = 'SAVED_ACTIONS_REQUEST';
export const SAVED_ACTIONS_SUCCESS = 'SAVED_ACTIONS_SUCCESS';
export const SAVED_ACTIONS_FAIL = 'SAVED_ACTIONS_FAIL';

// Ongoing
export const ONGOING_ACTIONS_REQUEST = 'ONGOING_ACTIONS_REQUEST';
export const ONGOING_ACTIONS_SUCCESS = 'ONGOING_ACTIONS_SUCCESS';
export const ONGOING_ACTIONS_FAIL = 'ONGOING_ACTIONS_FAIL';

// New
export const NEW_ACTIONS_REQUEST = 'NEW_ACTIONS_REQUEST';
export const NEW_ACTIONS_SUCCESS = 'NEW_ACTIONS_SUCCESS';
export const NEW_ACTIONS_FAIL = 'NEW_ACTIONS_FAIL';

// Automated
export const AUTOMATED_ACTIONS_REQUEST = 'AUTOMATED_ACTIONS_REQUEST';
export const AUTOMATED_ACTIONS_SUCCESS = 'AUTOMATED_ACTIONS_SUCCESS';
export const AUTOMATED_ACTIONS_FAIL = 'AUTOMATED_ACTIONS_FAIL';

// Save new
export const SAVE_ACTION_REQUEST = 'SAVE_ACTION_REQUEST';
export const SAVE_ACTION_SUCCESS = 'SAVE_ACTION_SUCCESS';
export const SAVE_ACTION_FAIL = 'SAVE_ACTION_FAIL';

// Remove
export const REMOVE_ACTION_REQUEST = 'REMOVE_ACTION_REQUEST';
export const REMOVE_ACTION_SUCCESS = 'REMOVE_ACTION_SUCCESS';
export const REMOVE_ACTION_FAIL = 'REMOVE_ACTION_FAIL';

// Complete
export const COMPLETE_ACTION_REQUEST = 'COMPLETE_ACTION_REQUEST';
export const COMPLETE_ACTION_SUCCESS = 'COMPLETE_ACTION_SUCCESS';
export const COMPLETE_ACTION_FAIL = 'COMPLETE_ACTION_FAIL';

// Failed
export const FAILED_ACTION_REQUEST = 'FAILED_ACTION_REQUEST';
export const FAILED_ACTION_SUCCESS = 'FAILED_ACTION_SUCCESS';
export const FAILED_ACTION_FAIL = 'FAILED_ACTION_FAIL';

// Automate
export const AUTOMATE_ACTION_REQUEST = 'AUTOMATE_ACTION_REQUEST';
export const AUTOMATE_ACTION_SUCCESS = 'AUTOMATE_ACTION_SUCCESS';
export const AUTOMATE_ACTION_FAIL = 'AUTOMATE_ACTION_FAIL';

// Not Automate
export const NOT_AUTOMATE_ACTION_REQUEST = 'NOT_AUTOMATE_ACTION_REQUEST';
export const NOT_AUTOMATE_ACTION_SUCCESS = 'NOT_AUTOMATE_ACTION_SUCCESS';
export const NOT_AUTOMATE_ACTION_FAIL = 'NOT_AUTOMATE_ACTION_FAIL';

// Create
export const CREATE_ACTION_REQUEST = 'CREATE_ACTION_REQUEST';
export const CREATE_ACTION_SUCCESS = 'CREATE_ACTION_SUCCESS';
export const CREATE_ACTION_FAIL = 'CREATE_ACTION_FAIL';

// Delete
export const DELETE_ACTION_REQUEST = 'DELETE_ACTION_REQUEST';
export const DELETE_ACTION_SUCCESS = 'DELETE_ACTION_SUCCESS';
export const DELETE_ACTION_FAIL = 'DELETE_ACTION_FAIL';

// Modify
export const MODIFY_ACTION_REQUEST = 'MODIFY_ACTION_REQUEST';
export const MODIFY_ACTION_SUCCESS = 'MODIFY_ACTION_SUCCESS';
export const MODIFY_ACTION_FAIL = 'MODIFY_ACTION_FAIL';

// Reset Action Form
export const FORM_ACTION_RESET = 'FORM_ACTION_RESET';

// By author
export const AUTHOR_ACTIONS_REQUEST = 'AUTHOR_ACTIONS_REQUEST';
export const AUTHOR_ACTIONS_SUCCESS = 'AUTHOR_ACTIONS_SUCCESS';
export const AUTHOR_ACTIONS_FAIL = 'AUTHOR_ACTIONS_FAIL';

// Share
export const SHARE_ACTION_REQUEST = 'SHARE_ACTION_REQUEST';
export const SHARE_ACTION_SUCCESS = 'SHARE_ACTION_SUCCESS';
export const SHARE_ACTION_FAIL = 'SHARE_ACTION_FAIL';
