// Get Course
export const CURRENT_EVENT_REQUEST = 'CURRENT_EVENT_REQUEST';
export const CURRENT_EVENT_SUCCESS = 'CURRENT_EVENT_SUCCESS';
export const CURRENT_EVENT_FAILED = 'CURRENT_EVENT_FAILED';

// Survey
export const GET_SURVEY_REQUEST = 'GET_SURVEY_REQUEST';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const GET_SURVEY_FAILED = 'GET_SURVEY_FAILED';

export const POST_SURVEY_REQUEST = 'POST_SURVEY_REQUEST';
export const POST_SURVEY_SUCCESS = 'POST_SURVEY_SUCCESS';
export const POST_SURVEY_FAILED = 'POST_SURVEY_FAILED';

export const GET_SURVEY_RESULTS_REQUEST = 'GET_SURVEY_RESULTS_REQUEST';
export const GET_SURVEY_RESULTS_SUCCESS = 'GET_SURVEY_RESULTS_SUCCESS';
export const GET_SURVEY_RESULTS_FAILED = 'GET_SURVEY_RESULTS_FAILED';
