// Get Courses
export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILED = 'GET_COURSES_FAILED';

// Get Course
export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST';
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAILED = 'COURSE_DETAILS_FAILED';

// Get Course Progress
export const UPDATE_COURSE_PROGRESS_REQUEST = 'UPDATE_COURSE_PROGRESS_REQUEST';
export const UPDATE_COURSE_PROGRESS_SUCCESS = 'UPDATE_COURSE_PROGRESS_SUCCESS';
export const UPDATE_COURSE_PROGRESS_FAILED = 'UPDATE_COURSE_PROGRESS_FAILED';
