// Get People
export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAILED = 'GET_PEOPLE_FAILED';

// Get Following
export const GET_FOLLOWING_REQUEST = 'GET_FOLLOWING_REQUEST';
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS';
export const GET_FOLLOWING_FAILED = 'GET_FOLLOWING_FAILED';

// Get Feed
export const GET_FEED_REQUEST = 'GET_FEED_REQUEST';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export const GET_FEED_FAILED = 'GET_FEED_FAILED';

// Get Followers
export const GET_FOLLOWERS_REQUEST = 'GET_FOLLOWERS_REQUEST';
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';
export const GET_FOLLOWERS_FAILED = 'GET_FOLLOWERS_FAILED';

// Get Search
export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_SEARCH_FAILED = 'GET_SEARCH_FAILED';
export const EMPTY_SEARCH = 'EMPTY_SEARCH';

// Get Person
export const PERSON_DETAILS_REQUEST = 'PERSON_DETAILS_REQUEST';
export const PERSON_DETAILS_SUCCESS = 'PERSON_DETAILS_SUCCESS';
export const PERSON_DETAILS_FAILED = 'PERSON_DETAILS_FAILED';

// Follow Person
export const FOLLOW_PERSON_REQUEST = 'FOLLOW_PERSON_REQUEST';
export const FOLLOW_PERSON_SUCCESS = 'FOLLOW_PERSON_SUCCESS';
export const FOLLOW_PERSON_FAILED = 'FOLLOW_PERSON_FAILED';

// Unfollow Person
export const UNFOLLOW_PERSON_REQUEST = 'UNFOLLOW_PERSON_REQUEST';
export const UNFOLLOW_PERSON_SUCCESS = 'UNFOLLOW_PERSON_SUCCESS';
export const UNFOLLOW_PERSON_FAILED = 'UNFOLLOW_PERSON_FAILED';
