# Generated by Django 5.1.3 on 2024-11-14 00:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=39, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('caption', models.CharField(max_length=150)),
                ('duration', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year'), ('once', 'once')], max_length=5)),
                ('level', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6)),
                ('SDGs', models.ManyToManyField(to='actions.sdg')),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('last_activation', models.DateField(default=datetime.date.today)),
                ('completed_times', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
