# Generated by Django 5.1.4 on 2025-01-15 21:32

import actions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='author',
            field=models.ForeignKey(default=actions.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='action',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
