# Generated by Django 5.1.4 on 2025-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_author_action_description_action_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
